server:
  port: 8888
spring:
  datasource:
    name: test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 50 # 最大连接数
    initialSize: 1 # 初始化大小
    maxWait: 60000 # 获取连接超时时间
    minIdle: 1 # 最小连接数
    timeBetweenEvictionRunsMillis: 60000 # 间隔多久检测一次，关闭空闲的连接
    minEvictableIdleTimeMillis: 300000 # 一个连接在池中的最小生存时间
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 50
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true


######################################
blog:
  desKey: '123456'